# Generated by Django 2.2.5 on 2020-05-06 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日付')),
                ('weight', models.IntegerField(help_text='単位はkg', verbose_name='体重')),
                ('calorie_intake', models.IntegerField(help_text='単位はkcal', verbose_name='カロリー')),
                ('protein', models.IntegerField(help_text='単位はg', verbose_name='タンパク質')),
            ],
            options={
                'verbose_name': '栄養',
                'verbose_name_plural': '栄養',
                'db_table': 'meal',
            },
        ),
    ]
