# Generated by Django 2.2.5 on 2020-05-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='bentipress',
            field=models.IntegerField(default=1, help_text='単位はkg', verbose_name='ベンチプレス'),
            preserve_default=False,
        ),
    ]
